[package]
name = 'my_todo_list'
version = '1.0.0'
[dependencies.CreditChainFramework]
git = 'https://github.com/creditchainorg/creditchain-framework.git'
rev = 'main'
subdir = 'creditchain-framework'
[addresses]
todolist_addr='_'