[package]
name = "CliArgs"
version = "0.1.0"
upgrade_policy = "compatible"

[addresses]
test_account = "_"

[dependencies.CreditChainFramework]
git = "https://github.com/creditchainorg/creditchain-framework.git"
subdir = "creditchain-framework"
rev = "mainnet"