[package]
name = 'ambassador_token'
version = '1.0.0'

# do not change to "_", concrete address needed for module-publish testing framework
[addresses]
ambassador = "0xCAFE"

[dependencies]
CreditChainFramework = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "creditchain-framework", rev = "mainnet" }
CreditChainTokenObjects = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "creditchain-token-objects", rev = "mainnet" }
