[package]
name = "calculator"
version = "0.0.0"

[addresses]
account = "_"

[dependencies]
CreditChainFramework = { local = "../../../framework/creditchain-framework" }
CreditChainStdlib = { local = "../../../framework/creditchain-stdlib" }
