[package]
name = "creditchain-network-discovery"
description = "CreditChain Network Peer Discovery"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-channels = { workspace = true }
creditchain-config = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-event-notifications = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-network = { workspace = true }
creditchain-rest-client = { workspace = true }
creditchain-short-hex-str = { workspace = true }
creditchain-time-service = { workspace = true }
creditchain-types = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[dev-dependencies]
creditchain-config = { workspace = true, features = ["testing"] }
creditchain-netcore = { workspace = true, features = ["fuzzing"] }
creditchain-temppath = { workspace = true }
rand = { workspace = true }
