[package]
name = "creditchain-vm-profiling"
version = "0.1.1"
authors = ["CreditChain Research Team <research@creditchain.io>"]
repository = "https://github.com/ibankio/creditchain"
homepage = "https://creditchain.io"
license = "Apache-2.0"
publish = false
edition = "2021"
default-run = "main"

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
glob = { workspace = true }
once_cell = { workspace = true }
smallvec = { workspace = true }

creditchain-block-executor = { workspace = true }
creditchain-cached-packages = { workspace = true }
creditchain-gas-schedule = { workspace = true }
creditchain-move-stdlib = { workspace = true }
creditchain-native-interface = { workspace = true }
creditchain-table-natives = { workspace = true }
creditchain-transaction-simulation = { workspace = true }
creditchain-types = { workspace = true }
creditchain-vm = { workspace = true }

move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-ir-compiler = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-test-utils = { workspace = true }
move-vm-types = { workspace = true }

[[bin]]
name = "main"
path  = "src/main.rs"

[[bin]]
name = "run-move"
path = "src/bins/profile_move_bin.rs"

[[bin]]
name = "run-creditchain-p2p"
path = "src/bins/profile_creditchain_p2p_bin.rs"
