[package]
name = "creditchain-node-checker"
description = "CreditChain Node Health Checker"
version = "0.1.2"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-config = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-network-checker = { workspace = true }
creditchain-rest-client = { workspace = true }
creditchain-sdk = { workspace = true }
creditchain-transaction-emitter-lib = { workspace = true }
creditchain-transaction-workloads-lib = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
poem = { workspace = true }
poem-openapi = { workspace = true }
prometheus-parse = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[lib]
name = "creditchain_node_checker_lib"
path = "src/lib.rs"
