[package]
name = "creditchain-peer-monitoring-service-server"
description = "The peer monitoring service (server-side)"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
creditchain-bounded-executor = { workspace = true }
creditchain-build-info = { workspace = true }
creditchain-channels = { workspace = true }
creditchain-config = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-netcore = { workspace = true }
creditchain-network = { workspace = true }
creditchain-peer-monitoring-service-types = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-time-service = { workspace = true }
creditchain-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-network = { workspace = true, features = ["fuzzing"] }
creditchain-time-service = { workspace = true, features = ["testing"] }
claims = { workspace = true }
maplit = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
