[package]
name = "creditchain-storage-service-server"
description = "The CreditChain storage service (server-side)"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-channels = { workspace = true }
creditchain-config = { workspace = true }
creditchain-infallible = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-network = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-storage-service-notifications = { workspace = true }
creditchain-storage-service-types = { workspace = true }
creditchain-time-service = { workspace = true }
creditchain-types = { workspace = true }
arc-swap = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
mini-moka = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
creditchain-bitvec = { workspace = true }
creditchain-config = { workspace = true, features = ["fuzzing"] }
creditchain-crypto = { workspace = true }
creditchain-netcore = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-time-service = { workspace = true, features = ["async", "testing"] }
creditchain-types = { workspace = true }
claims = { workspace = true }
maplit = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
