[package]
name = "creditchain-indexer"
description = "CreditChain Indexer"
version = "0.0.2"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-api = { workspace = true }
creditchain-api-types = { workspace = true }
creditchain-bitvec = { workspace = true }
creditchain-config = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-mempool = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-runtimes = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bigdecimal = { workspace = true }
chrono = { workspace = true }
diesel = { workspace = true, features = [
    "chrono",
    "postgres",
    "r2d2",
    "numeric",
    "serde_json",
] }
diesel_migrations = { workspace = true }
field_count = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
creditchain-api-test-context = { workspace = true }
