[package]
name = "creditchain-keyless-pepper-example-client-rust"
description = "CreditChain Keyless pepper service"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
creditchain-crypto = { workspace = true }
creditchain-infallible = { workspace = true }
creditchain-keyless-pepper-common = { workspace = true }
creditchain-types = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-serialize = { workspace = true }
bcs = { workspace = true }
firestore = { workspace = true }
hex = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
