# :!:>manifest
[package]
name = 'UpgradeAndGovern'
version = '1.1.0'

[addresses]
upgrade_and_govern = '_'

[dependencies.CreditChainFramework]
git = "https://github.com/creditchainorg/creditchain-framework.git"
subdir = "creditchain-framework"
rev = "mainnet"