[package]
name = "creditchain-executor-types"
description = "CreditChain executor interface types"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-drop-helper = { workspace = true }
creditchain-infallible = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-scratchpad = { workspace = true }
creditchain-secure-net = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-types = { workspace = true }
bcs = { workspace = true }
criterion = { workspace = true }
derive_more = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
ouroboros = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
creditchain-types = { workspace = true, features = ["fuzzing"] }

[features]
default = []
fuzzing = ["creditchain-crypto/fuzzing", "creditchain-types/fuzzing"]
bench = []

[[bench]]
name = "default"
harness = false
