apiVersion: v2
name: creditchain-node
version: 1.0.0
appVersion: 1.0.0
description: CreditChain blockchain node deployment
home: https://creditchain.org/
sources:
- https://github.com/creditchainorg/creditchain-core
