[package]
name = "creditchain-vm"
description = "CreditChain VM runtime"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-aggregator = { workspace = true }
creditchain-block-executor = { workspace = true }
creditchain-block-partitioner = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-crypto-derive = { workspace = true }
creditchain-experimental-runtimes = { workspace = true }
creditchain-framework =  { workspace = true }
creditchain-gas-algebra = { workspace = true }
creditchain-gas-meter = { workspace = true }
creditchain-gas-schedule = { workspace = true }
creditchain-infallible = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-memory-usage-tracker = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-mvhashmap = { workspace = true }
creditchain-native-interface = { workspace = true }
creditchain-table-natives = { workspace = true }
creditchain-types = { workspace = true }
creditchain-vm-environment = { workspace = true }
creditchain-vm-logging = { workspace = true }
creditchain-vm-types = { workspace = true }
ark-bn254 = { workspace = true }
ark-groth16 = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
claims = { workspace = true }
crossbeam-channel = { workspace = true }
derive_more = { workspace = true }
fail = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-unit-test = { workspace = true, optional = true }
move-vm-metrics = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
ouroboros = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
creditchain-aggregator = { workspace = true, features = ["testing"] }
creditchain-block-executor = { workspace = true, features = ["testing"] }
creditchain-keygen = { workspace = true }
creditchain-language-e2e-tests = { workspace = true }
creditchain-transaction-simulation = { workspace = true }
creditchain-types = { workspace = true, features = ["fuzzing", "testing"] }
claims = { workspace = true }
move-vm-types = { workspace = true, features = ["testing"] }
proptest = { workspace = true }
rand_core = { workspace = true }
test-case = { workspace = true }

[features]
default = []
fuzzing = ["move-core-types/fuzzing", "move-binary-format/fuzzing", "move-vm-types/fuzzing", "creditchain-framework/fuzzing", "creditchain-types/fuzzing"]
failpoints = ["fail/failpoints", "move-vm-runtime/failpoints"]
testing = ["move-unit-test", "creditchain-framework/testing"]
