[package]
name = "fa_mint_transfer_burn"
version = "1.0.0"
authors = []

[addresses]

[dependencies]
CreditChainFramework = { local = "../../../../../../creditchain-move/framework/creditchain-framework" }
