[package]
name = "cli_e2e_tests"
version = "0.0.1"

[addresses]
addr = "_"

[dev-addresses]
addr = "0x12345"

[dependencies.CreditChainFramework]
git = "https://github.com/creditchainorg/creditchain-framework.git"
rev = "testnet"
subdir = "creditchain-framework"

[dependencies.CreditChainTokenObjects]
git = "https://github.com/creditchainorg/creditchain-framework.git"
rev = "testnet"
subdir = "creditchain-token-objects"
