[package]
name = "ResourceGroupsPrimary"
version = "0.0.0"

[addresses]
resource_groups_primary = "_"

[dependencies]
CreditChainFramework = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "creditchain-framework", rev = "mainnet" }
