[package]
name = "creditchain-db-indexer-schemas"
description = "CreditChainDB Internal Indexer DB schemas"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-schemadb = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-types = { workspace = true }
bcs = { workspace = true }
byteorder = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
serde = { workspace = true }

[dev-dependencies]
creditchain-proptest-helpers = { workspace = true }
creditchain-schemadb = { workspace = true, features = ["fuzzing"] }
creditchain-types = { workspace = true, features = ["fuzzing"] }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "creditchain-types/fuzzing", "creditchain-schemadb/fuzzing"]
