[package]
name = "creditchain-indexer-grpc-table-info"
version = "1.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-api = { workspace = true }
creditchain-api-types = { workspace = true }
creditchain-config = { workspace = true }
creditchain-db-indexer  = { workspace = true }
creditchain-indexer-grpc-fullnode = { workspace = true }
creditchain-indexer-grpc-utils = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-mempool = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-runtimes = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-types = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
google-cloud-storage = { workspace = true }
hyper = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
rocksdb = { workspace = true }
tempfile = { workspace = true }
