[package]
name = "creditchain-vm-types"
description = "CreditChain VM types"
version = "0.0.2"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
ambassador = { workspace = true }
anyhow = { workspace = true }
creditchain-aggregator = { workspace = true }
creditchain-gas-algebra = { workspace = true }
creditchain-gas-schedule = { workspace = true }
creditchain-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
claims = { workspace = true }
either = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
creditchain-aggregator = { workspace = true, features = ["testing"] }
creditchain-gas-schedule = { workspace = true, features = ["testing"] }
creditchain-transaction-simulation = { workspace = true }
creditchain-vm = { workspace = true }
test-case = { workspace = true }
