[package]
name = "creditchain-faucet-cli"
description = "CreditChain Faucet CLI"
version = "2.0.2"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-faucet-core = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-sdk = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }

