[package]
name = "empty"
version = "1.0.0"
authors = []

[addresses]
empty = "0xcafe"

[dev-addresses]

[dependencies.CreditChainFramework]
git = "https://github.com/creditchainorg/creditchain-framework.git"
rev = "mainnet"
subdir = "creditchain-framework"

[dev-dependencies]
