{{ $fullnode_statefulset := lookup "apps/v1" "StatefulSet" $.Release.Namespace (include "aptos-fullnode.fullname" .) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aptos-fullnode.fullname" . }}
  labels:
    {{- include "aptos-fullnode.labels" . | nindent 4 }}
    app.kubernetes.io/name: fullnode
spec:
  serviceName: {{ include "aptos-fullnode.fullname" . }}
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "aptos-fullnode.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: fullnode
  template:
    metadata:
      labels:
        {{- include "aptos-fullnode.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: fullnode
        {{- if or $.Values.chain.label $.Values.chain.name }}
        chain_name: {{ $.Values.chain.label | default $.Values.chain.name }}
        {{- end}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
        {{- if $.Values.metrics.destination }}
        aptos.dev/metrics-destination: {{ $.Values.metrics.destination }}
        {{- end}}
    spec:
      initContainers:
      {{- with .Values.restore }}
      {{- if .enabled }}
      - name: restore
        image: {{ .image.repo }}:{{ .image.tag | default $.Values.imageTag }}
        imagePullPolicy: {{ .image.pullPolicy }}
        resources:
          {{- toYaml .resources | nindent 10 }}
        args:
        - /bin/bash
        - -c
        - |-
          set -euxo pipefail
          # cleanup creditchaindb
          if [ -f /opt/creditchain/data/restore-failed ] || \
              [ ! -f /opt/creditchain/data/restore-uid ] || \
              [ "$(cat /opt/creditchain/data/restore-uid)" != "{{ .config.restore_epoch }}" ]; then
            rm -rf /opt/creditchain/data/db /opt/creditchain/data/restore-{complete,failed}
            echo "{{ .config.restore_epoch }}" > /opt/creditchain/data/restore-uid
          fi

          [ -f /opt/creditchain/data/restore-complete ] && exit 0
          # start restore process
          /usr/local/bin/creditchain-debugger creditchain-db restore bootstrap-db \
            --concurrent-downloads {{ .config.concurrent_downloads }} \
            {{ range .config.trusted_waypoints }} --trust-waypoint {{ . }}{{ end }} \
            --target-db-dir /opt/creditchain/data/db \
            --metadata-cache-dir /opt/creditchain/data/aptos-restore-metadata \
            --ledger-history-start-version {{ .config.start_version }} \
            {{- if .config.target_version }} --target-version {{- .config.target_version }}{{- end }}
            --command-adapter-config /opt/creditchain/etc/{{ .config.location }}.yaml

          if [ $? -gt 0 ]; then
            # mark restore as failed
            touch /opt/creditchain/data/restore-failed
            exit 1
          else
            # success, remove the marker
            rm -f /opt/creditchain/data/restore-failed
            touch /opt/creditchain/data/restore-complete
          fi
        env:
        - name: RUST_LOG
          value: "debug"
        - name: RUST_BACKTRACE
          value: "full"
        {{- if (include "backup.pushMetricsEndpoint" $) }}
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PUSH_METRICS_ENDPOINT
          value: "{{- include "backup.pushMetricsEndpoint" $ }}/api/v1/import/prometheus?extra_label=role={{- .jobName | default "db_restore" }}&extra_label=kubernetes_pod_name=$(KUBERNETES_POD_NAME)"
        {{- end }}
        - name: CONTROLLER_UID
          valueFrom:
            fieldRef:
              fieldPath: "metadata.labels['controller-uid']"
        {{- include "backup.backupEnvironment" (dict "config" .config "era" (default $.Values.chain.era .config.restore_era)) | nindent 8 }}
        volumeMounts:
        - name: backup-config
          mountPath: /opt/creditchain/etc
        - name: creditchain-data
          mountPath: /opt/creditchain/data
        - name: tmp
          mountPath: /tmp
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      {{- end }} # if .enabled
      {{- end }} # with .Values.restore
      containers:
      - name: fullnode
        {{- if and $fullnode_statefulset (not $.Values.manageImages) }} # if the statefulset already exists and we do not want helm to simply overwrite the image, use the existing image
        image: {{ (first $fullnode_statefulset.spec.template.spec.containers).image }}
        {{- else }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag | default $.Values.imageTag }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - /bin/bash
        - -c
        - |-
          set -euxo pipefail
          if [[ -f /opt/creditchain/data/wipe-db ]]; then
            # Wipe DB
            rm -rf /opt/creditchain/data/db
            # Delete the command file so we only wipe the DB once
            rm -vf /opt/creditchain/data/wipe-db
          fi
          {{- if and (not .Values.chain.genesisConfigmap) (not .Values.chain.genesisSecret) }}
          # Download genesis and waypoint if necessary
          curl -o /opt/creditchain/genesis/waypoint.txt {{ (get .Values.creditchain_chains .Values.chain.name).waypoint_txt_url }}
          curl -o /opt/creditchain/genesis/genesis.blob {{ (get .Values.creditchain_chains .Values.chain.name).genesis_blob_url }}
          {{- end }}
          # Start the node
          exec /usr/local/bin/creditchain-node -f /opt/creditchain/etc/fullnode.yaml
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: RUST_LOG
          value: {{ .Values.rust_log }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RUST_BACKTRACE
          value: "0"
        volumeMounts:
        - name: creditchain-config
          mountPath: /opt/creditchain/etc
        - name: creditchain-genesis
          mountPath: /opt/creditchain/genesis
        - name: creditchain-data
          mountPath: /opt/creditchain/data
        - name: tmp
          mountPath: /tmp
        ports:
        - containerPort: 6182
        - containerPort: 6186
        - containerPort: 8081
        - containerPort: 8080
          name: api
        - containerPort: 9101
          name: metrics
        - containerPort: 9102
          name: admin
        # NOTE: these require the API to be enabled, which is not always the case
        # Wait for up to 20 * 15 = 300 seconds before starting the liveness and readiness probes.
        startupProbe:
          httpGet:
            path: /v1/-/healthy
            port: 8080
          timeoutSeconds: 5
          failureThreshold: 20
          periodSeconds: 15
        # Restart the pod if the REST API is ever unresponsive for 60 seconds.
        livenessProbe:
          httpGet:
            path: /v1/-/healthy
            port: 8080
          timeoutSeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 4
         # Pod is ready when state sync is caught up.
         # If it falls more than 10 seconds behind, remove it from the service.
        readinessProbe:
          httpGet:
            path: /v1/-/healthy?duration_secs=10
            port: 8080
          timeoutSeconds: 5
          periodSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 6180
        runAsGroup: 6180
        fsGroup: 6180
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: creditchain-config
        configMap:
          name: {{ include "aptos-fullnode.fullname" . }}
      - name: creditchain-genesis
      {{- if .Values.chain.genesisConfigmap }}
        configMap:
          name: {{ .Values.chain.genesisConfigmap }}
      {{- else if .Values.chain.genesisSecret }}
        secret:
          secretName: {{ .Values.chain.genesisSecret }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: creditchain-data
        persistentVolumeClaim:
          claimName: {{ include "aptos-fullnode.fullname" . }}-e{{ .Values.chain.era }}
      - name: backup-config
        configMap:
          name: {{ include "backup.fullname" . }}-backup
      - name: tmp
        emptyDir: {}
      serviceAccountName: {{ include "aptos-fullnode.serviceAccountName" . }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{.Values.imagePullSecret}}
      {{- end }}
