[package]
name = "creditchain-transaction-emitter"
description = "CreditChain transaction emitter for testing"
version = "0.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-global-constants = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-sdk = { workspace = true }
creditchain-transaction-emitter-lib = { workspace = true }
creditchain-transaction-workloads-lib = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
