blank_issues_enabled: true
contact_links:
  - name: Questions and Help (on CreditChain Developer Discussions)
    url: https://github.com/ibankio/creditchain/discussions
    about: Support and other Questions are handled by the team and the community on CreditChain Developer Discussions.
  - name: Security Reporting
    url: https://github.com/ibankio/creditchain/security
    about: Report security issues via the repository security workflow.
