[package]
name = "creditchain-workspace-server"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
# libra2 deps
creditchain-cached-packages = { workspace = true }
creditchain-config = { workspace = true }
creditchain-faucet-core = { workspace = true }
creditchain-localnet = { workspace = true }
creditchain-node = { workspace = true }
creditchain-types = { workspace = true }

# third party deps
anyhow = { workspace = true }
bollard = { workspace = true }
clap = { workspace = true }
diesel = { workspace = true, features = ["postgres_backend"] }
diesel-async = { workspace = true }
futures = { workspace = true }
maplit = { workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

# indexer deps
libra2-indexer-processor-sdk = { workspace = true, features = ["postgres_partial"] }
processor = { workspace = true }
