[package]
name = "creditchain-state-sync-driver"
description = "The driver for state sync"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-config = { workspace = true }
creditchain-consensus-notifications = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-data-client = { workspace = true }
creditchain-data-streaming-service = { workspace = true }
creditchain-event-notifications = { workspace = true }
creditchain-executor-types = { workspace = true }
creditchain-infallible = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-mempool-notifications = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-runtimes = { workspace = true }
creditchain-schemadb = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-storage-service-notifications = { workspace = true }
creditchain-time-service = { workspace = true }
creditchain-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
creditchain-channels = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-db = { workspace = true }
creditchain-executor = { workspace = true }
creditchain-executor-test-helpers = { workspace = true }
creditchain-genesis = { workspace = true, features = ["testing"] }
creditchain-network = { workspace = true }
creditchain-storage-service-client = { workspace = true }
creditchain-storage-service-types = { workspace = true }
creditchain-temppath = { workspace = true }
creditchain-time-service = { workspace = true, features = ["async", "testing"] }
creditchain-vm = { workspace = true }
creditchain-vm-genesis = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
claims = { workspace = true }
mockall = { workspace = true }
move-core-types = { workspace = true }
ntest = { workspace = true }
rand = { workspace = true }
