[package]
name = "framework_usecases"
version = "0.0.0"

[dependencies]
CreditChainFramework = { local = "../../../../creditchain-move/framework/creditchain-framework" }
CreditChainToken = { local = "../../../../creditchain-move/framework/creditchain-token" }
CreditChainTokenObjects = { local = "../../../../creditchain-move/framework/creditchain-token-objects" }

# testing exchanging of constant address works as well.
[addresses]
publisher_address = "0xABCD"
