[package]
name = "CommonAccount"
version = "1.0.0"

[dependencies]
CreditChainFramework = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "creditchain-framework", rev = "mainnet" }

[addresses]
common_account = "_"
