[package]
name = "creditchain-executor-benchmark"
description = "CreditChain executor benchmark"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-aggregator = { workspace = true }
creditchain-block-executor = { workspace = true }
creditchain-block-partitioner = { workspace = true }
creditchain-config = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-db = { workspace = true }
creditchain-executor = { workspace = true }
creditchain-executor-service = { workspace = true }
creditchain-executor-types = { workspace = true }
creditchain-experimental-ptx-executor = { workspace = true }
creditchain-experimental-runtimes = { workspace = true }
creditchain-genesis = { workspace = true, features = ["testing"] }
creditchain-infallible = { workspace = true }
creditchain-jellyfish-merkle = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-mvhashmap = { workspace = true }
creditchain-node-resource-metrics = { workspace = true }
creditchain-push-metrics =  { workspace = true }
creditchain-sdk = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-transaction-generator-lib = { workspace = true }
creditchain-transaction-workloads-lib = { workspace = true }
creditchain-types = { workspace = true }
creditchain-vm = { workspace = true }
creditchain-vm-environment = { workspace = true }
creditchain-vm-logging = { workspace = true }
creditchain-vm-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
move-core-types = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thread_local = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }

[target.'cfg(unix)'.dependencies]
creditchain-profiler = { workspace = true }
jemallocator = { version = "0.5.0", features = [
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }

[dev-dependencies]
creditchain-temppath = { workspace = true }

[features]
default = []
fuzzing = ["creditchain-config/fuzzing", "creditchain-crypto/fuzzing", "creditchain-types/fuzzing"]
