[package]
name = "creditchain-transactional-test-harness"
description = "Transactional testing framework for Move"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-api-types = { workspace = true }
creditchain-block-executor = { workspace = true }
creditchain-cached-packages = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-framework = { workspace = true }
creditchain-gas-schedule = { workspace = true }
creditchain-resource-viewer = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-transaction-simulation = { workspace = true }
creditchain-types = { workspace = true, features = ["fuzzing"] }
creditchain-vm = { workspace = true }
creditchain-vm-environment = { workspace = true }
creditchain-vm-genesis = { workspace = true }
creditchain-vm-types = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
codespan-reporting = { workspace = true }
hex = { workspace = true }
move-binary-format = { workspace = true, features = ["fuzzing"] }
move-bytecode-verifier = { workspace = true }
move-command-line-common = { workspace = true }
move-compiler-v2 = { workspace = true }
move-core-types = { workspace = true, features = ["fuzzing"] }
move-model = { workspace = true }
move-symbol-pool = { workspace = true }
move-transactional-test-runner = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
once_cell = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
creditchain-types = { workspace = true, features = ["fuzzing"] }
datatest-stable = { workspace = true }

[[test]]
name = "tests"
harness = false
