[package]
name = "creditchain-testcases"
description = "CreditChain compatibility tests"
version = "0.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain = { workspace = true, features = ["fuzzing"] }
creditchain-config = { workspace = true }
creditchain-forge = { workspace = true }
creditchain-global-constants = { workspace = true }
creditchain-keygen = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-release-builder = { workspace = true }
creditchain-rest-client = { workspace = true }
creditchain-runtimes = { workspace = true }
creditchain-sdk = { workspace = true }
creditchain-temppath = { workspace = true }
creditchain-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
assert_approx_eq = { workspace = true }

[[test]]
name = "forge-local-compatibility"
harness = false

[[test]]
name = "forge-local-performance"
harness = false
