[package]
name = "creditchain-keyless-pepper-service"
description = "CreditChain Keyless pepper service"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aes-gcm = { workspace = true }
anyhow = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-infallible = { workspace = true }
creditchain-inspection-service = { workspace = true }
creditchain-keyless-pepper-common = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-types = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-groth16 = { workspace = true }
ark-serialize = { workspace = true }
bcs = { workspace = true }
dashmap = { workspace = true }
firestore = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
jsonwebtoken = { workspace = true }
jwt = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
