[package]
name = "integration-tests"
description = "Indexer GRPC processor integration tests."
version = "1.0.0"

# Workspace inherited keys
authors = ["CreditChain Research Team"]
edition = "2021"
homepage = "https://github.com/ibankio/creditchain"
license = "Apache-2.0"
publish = false
repository = "https://github.com/ibankio/creditchain"
rust-version = { workspace = true }

[dependencies]
ahash = { workspace = true }
anyhow = { workspace = true }
libra2-indexer-processor-sdk = { workspace = true }
creditchain-indexer-test-transactions = { workspace = true }
assert-json-diff = { workspace = true }
bigdecimal = { workspace = true }
chrono = { workspace = true }
diesel = { workspace = true }
field_count = { workspace = true }
processor = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
ahash = { workspace = true }
libra2-indexer-processor-sdk = { workspace = true, features = [
    "testing_framework",
] }
futures = { workspace = true }
processor = { workspace = true }
tempfile = { workspace = true }
tonic = { workspace = true }
url = { workspace = true }
