[package]
name = "Event-example"
version = "0.0.1"

[addresses]
std = "0x1"
creditchain_framework = "0x1"
event = "_"

[dependencies]
CreditChainFramework = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "creditchain-framework", rev = "mainnet" }
