[package]
name = "ArgumentExample"
version = "0.0.0"

[addresses]
deploy_address = "_"

[dependencies]
CreditChainFramework = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "creditchain-framework", rev = "mainnet" }
