[package]
name = "ResourceGroupsSecondary"
version = "0.0.0"

[addresses]
resource_groups_primary = "_"
resource_groups_secondary = "_"

[dependencies]
CreditChainFramework = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "creditchain-framework", rev = "mainnet" }
ResourceGroupsPrimary = { local = "../primary" }
