apiVersion: v2
name: creditchain-genesis
version: 0.1.0
appVersion: 0.1.0
description: CreditChain blockchain automated genesis ceremony for testnets
home: https://creditchain.org/
sources:
- https://github.com/creditchainorg/creditchain-core
