apiVersion: v2
name: libra2-genesis
version: 0.1.0
appVersion: 0.1.0
description: Libra2 blockchain automated genesis ceremony for testnets
home: https://libra2.org/
sources:
- https://github.com/libra2org/libra2-core
