[package]
name = "smoke-test"
description = "CreditChain end to end tests"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain = { workspace = true, features = ["fuzzing"] }
creditchain-api-types = { workspace = true }
creditchain-bitvec = { path = "../../crates/creditchain-bitvec" }
creditchain-cached-packages = { workspace = true }
creditchain-config = { workspace = true, features = ["smoke-test"] }
creditchain-consensus = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-db = { workspace = true }
creditchain-db-indexer-schemas = { workspace = true }
creditchain-dkg = { workspace = true }
creditchain-faucet-core = { workspace = true }
creditchain-forge = { workspace = true }
creditchain-framework = { workspace = true }
creditchain-gas-algebra = { workspace = true }
creditchain-gas-schedule = { workspace = true, features = ["testing"] }
creditchain-global-constants = { workspace = true }
creditchain-indexer = { workspace = true }
creditchain-indexer-grpc-table-info = { workspace = true }
creditchain-inspection-service = { workspace = true }
creditchain-keygen = { workspace = true }
creditchain-move-debugger = { workspace = true }
creditchain-release-builder = { workspace = true }
creditchain-rest-client = { workspace = true }
creditchain-rosetta = { workspace = true }
creditchain-schemadb = { workspace = true }
creditchain-sdk = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-temppath = { workspace = true }
creditchain-transaction-filters = { workspace = true }
creditchain-types = { workspace = true }
creditchain-vm = { workspace = true }
bcs = { workspace = true }
diesel = { workspace = true, features = [
    "chrono",
    "postgres",
    "r2d2",
    "numeric",
    "serde_json",
] }
digest = { workspace = true }
ethers = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
creditchain-backup-cli = { workspace = true }
creditchain-db-indexer = { workspace = true, features = ["fuzzing"] }
creditchain-genesis = { workspace = true }
creditchain-infallible = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-secure-storage = { workspace = true }
creditchain-time-service = { workspace = true }
creditchain-vault-client = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }
