[package]
name = "creditchain-peer-monitoring-service-client"
description = "The CreditChain peer monitoring service (client-side)"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
creditchain-channels = { workspace = true }
creditchain-config = { workspace = true }
creditchain-id-generator = { workspace = true }
creditchain-infallible = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-network = { workspace = true }
creditchain-peer-monitoring-service-types = { workspace = true }
creditchain-time-service = { workspace = true }
creditchain-types = { workspace = true }
enum_dispatch = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
creditchain-build-info = { workspace = true }
creditchain-config = { workspace = true }
creditchain-netcore = { workspace = true }
creditchain-network = { workspace = true, features = ["fuzzing"] }
creditchain-peer-monitoring-service-server = { workspace = true }
bcs = { workspace = true }
maplit = { workspace = true }
tokio-stream = { workspace = true }
