[package]
name = "creditchain-forge"
description = "CreditChain end to end test framework"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
again = { workspace = true }
anyhow = { workspace = true, features = ["backtrace"] }
creditchain = { workspace = true }
creditchain-cached-packages = { workspace = true }
creditchain-cli-common = { workspace = true }
creditchain-config = { workspace = true }
creditchain-db = { workspace = true }
creditchain-framework = { workspace = true }
creditchain-genesis = { workspace = true }
creditchain-global-constants = { workspace = true }
creditchain-infallible = { workspace = true }
creditchain-inspection-service = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-rest-client = { workspace = true }
creditchain-retrier = { workspace = true }
creditchain-runtimes = { workspace = true }
creditchain-sdk = { workspace = true }
creditchain-short-hex-str = { workspace = true }
creditchain-state-sync-driver = { workspace = true }
creditchain-transaction-emitter-lib = { workspace = true }
creditchain-transaction-generator-lib = { workspace = true }
creditchain-transaction-workloads-lib = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["env", "unstable-styles"] }
either = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
itertools = { workspace = true }
json-patch = { workspace = true }
k8s-openapi = { version = "0.13.1", default-features = false, features = [
    "v1_22",
] }
kube = { version = "0.65.0", default-features = false, features = ["jsonpatch", "client", "rustls-tls", "derive"] }
log = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
prometheus-http-query = { workspace = true }
quick-junit = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sugars = { workspace = true }
tempfile = { workspace = true }
termcolor = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
serde_merge = { workspace = true }

[features]
default = []
testing = ["creditchain-global-constants/testing"]
