[package]
name = "creditchain-executor"
description = "CreditChain executor"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-block-executor = { workspace = true }
creditchain-consensus-types = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-drop-helper = { workspace = true }
creditchain-executor-service = { workspace = true }
creditchain-executor-types = { workspace = true }
creditchain-experimental-runtimes = { workspace = true }
creditchain-indexer-grpc-table-info = { workspace = true }
creditchain-infallible = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-sdk = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-types = { workspace = true }
creditchain-vm = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
fail = { workspace = true }
itertools = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
creditchain-cached-packages = { workspace = true }
creditchain-config = { workspace = true }
creditchain-db = { workspace = true }
creditchain-db-indexer = { workspace = true, features = ["fuzzing"] }
creditchain-executor-test-helpers = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-temppath = { workspace = true }
creditchain-transaction-simulation = { workspace = true }
creditchain-types = { workspace = true, features = ["testing"] }
creditchain-vm-genesis = { workspace = true }
arr_macro = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["creditchain-consensus-types/fuzzing", "creditchain-crypto/fuzzing", "creditchain-types/fuzzing", "creditchain-storage-interface/fuzzing"]
failpoints = ["fail/failpoints", "creditchain-vm/failpoints"]
consensus-only-perf-test = []

[[bench]]
name = "data_collection"
harness = false
