[package]
name = "fa_double_transfer"
version = "1.0.1"
authors = []

[addresses]

[dependencies]
CreditChainFramework = { local = "../../../../../../creditchain-move/framework/creditchain-framework" }
