[package]
name = "creditchain-replay-benchmark"
version = "0.1.1"
description = "A tool to replay and locally benchmark on-chain transactions."

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-block-executor = { workspace = true }
creditchain-framework = { workspace = true }
creditchain-gas-schedule = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-move-debugger = { workspace = true }
creditchain-push-metrics = { workspace = true }
creditchain-rest-client = { workspace = true }
creditchain-types = { workspace = true }
creditchain-vm = { workspace = true }
creditchain-vm-environment = { workspace = true }
bcs = { workspace = true }
claims = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
move-core-types = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[dev-dependencies]
creditchain-crypto = { workspace = true }
creditchain-types = { workspace = true, features = ["testing"] }
rand = { workspace = true }
