[package]
name = "Examples"
version = "0.0.0"

[addresses]
creditchain_framework = "0x1"
FACoin = "_"

[dependencies]
CreditChainFramework = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "creditchain-framework", rev = "mainnet" }
