[package]
name = "creditchain-resource-viewer"
description = "CreditChain resource viewer"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-types = { workspace = true }
creditchain-vm = { workspace = true }
creditchain-vm-environment = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-utils = { workspace = true }
move-core-types = { workspace = true }
move-resource-viewer = { workspace = true }
