[package]
name = "TooLargeTest"
version = "0.0.0"

[dependencies]
CreditChainFramework = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "creditchain-framework", rev = "mainnet" }
MoveStdlib = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "move-stdlib", rev = "mainnet" }
