[package]
name = "creditchain-storage-service-types"
description = "Common types offered by the CreditChain storage service"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
creditchain-compression = { workspace = true }
creditchain-config = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-time-service = { workspace = true }
creditchain-types = { workspace = true }
bcs = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
creditchain-time-service = { workspace = true, features = ["testing"] }
claims = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
