[package]
name = "creditchain-indexer-grpc-fullnode"
description = "CreditChain Indexer GRPC runtime on fullnode."
version = "1.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }

creditchain-api = { workspace = true }
creditchain-api-types = { workspace = true }
creditchain-bitvec = { workspace = true }
creditchain-config = { workspace = true }
creditchain-indexer-grpc-utils = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-mempool = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-moving-average = { workspace = true }
creditchain-protos = { workspace = true }
creditchain-runtimes = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-types = { workspace = true }

move-core-types = { workspace = true }

[dev-dependencies]
goldenfile = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }

creditchain-api-test-context = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-db = { workspace = true }
creditchain-executor = { workspace = true }
creditchain-executor-types = { workspace = true }
creditchain-framework = { workspace = true }
creditchain-genesis = { workspace = true }
creditchain-global-constants = { workspace = true }
creditchain-mempool = { workspace = true }
creditchain-mempool-notifications = { workspace = true }
creditchain-proptest-helpers = { workspace = true }
creditchain-sdk = { workspace = true }
creditchain-secure-storage = { workspace = true }
creditchain-temppath = { workspace = true }
creditchain-vm = { workspace = true }
creditchain-vm-validator = { workspace = true }
