[package]
name = "TransactationTests"
version = "0.0.0"

[addresses]
entry_func_failed= "0x1"

[dependencies]
CreditChainFramework = { local = "../../../creditchain-move/framework/creditchain-framework" }
