[package]
name = "creditchain"
description = "CreditChain tool for management of nodes and interacting with the blockchain"
version = "7.7.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
creditchain-api-types = { workspace = true }
creditchain-backup-cli = { workspace = true }
creditchain-bitvec = { workspace = true }
creditchain-build-info = { workspace = true }
creditchain-cached-packages = { workspace = true }
creditchain-cli-common = { workspace = true }
# creditchain-cli-common = { workspace = true }
creditchain-config = { workspace = true }
creditchain-crypto = { workspace = true }
creditchain-faucet-core = { workspace = true }
creditchain-framework = { workspace = true }
creditchain-gas-profiling = { workspace = true }
creditchain-gas-schedule = { workspace = true }
creditchain-genesis = { workspace = true }
creditchain-github-client = { workspace = true }
creditchain-global-constants = { workspace = true }
creditchain-indexer-grpc-server-framework = { workspace = true }
libra2-indexer-processor-sdk = { workspace = true }
creditchain-keygen = { workspace = true }
creditchain-ledger = { workspace = true }
creditchain-localnet = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-move-debugger = { workspace = true }
creditchain-network-checker = { workspace = true }
creditchain-node = { workspace = true }
creditchain-rest-client = { workspace = true }
creditchain-sdk = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-telemetry = { workspace = true }
creditchain-temppath = { workspace = true }
creditchain-types = { workspace = true }
creditchain-vm = { workspace = true, features = ["testing"] }
creditchain-vm-environment = { workspace = true }
creditchain-vm-genesis = { workspace = true }
creditchain-vm-logging = { workspace = true }
creditchain-vm-types = { workspace = true }
creditchain-workspace-server = { workspace = true }
async-trait = { workspace = true }
backoff = { workspace = true }
base64 = { workspace = true }
bcs = { workspace = true }
bollard = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["env", "unstable-styles", "wrap_help"] }
clap_complete = { workspace = true }
colored = { workspace = true }
dashmap = { workspace = true }
diesel = { workspace = true, features = ["postgres_backend"] }
diesel-async = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
legacy-move-compiler = { workspace = true }
maplit = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-source-map = { workspace = true }
move-cli = { workspace = true }
move-command-line-common = { workspace = true }
move-compiler-v2 = { workspace = true }
move-core-types = { workspace = true }
move-coverage = { workspace = true }
move-disassembler = { workspace = true }
move-ir-types = { workspace = true }
move-linter = { workspace = true }
move-model = { workspace = true }
move-package = { workspace = true }
move-prover-boogie-backend = { workspace = true }
move-symbol-pool = { workspace = true }
move-unit-test = { workspace = true, features = ["debugging"] }
move-vm-runtime = { workspace = true, features = ["testing"] }
open = { workspace = true }
pathsearch = { workspace = true }
poem = { workspace = true }
processor = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
self_update = { git = "https://github.com/banool/self_update.git", rev = "8306158ad0fd5b9d4766a3c6bf967e7ef0ea5c4b", features = [
    "archive-zip",
    "compression-zip-deflate",
] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
set_env = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { version = "0.5.0", features = [
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }

[features]
default = []
fuzzing = []
no-upload-proposal = []
indexer = ["creditchain-node/indexer"]
cli-framework-test-move = []

[build-dependencies]
shadow-rs = { workspace = true }
