[package]
name = "creditchain-executor-service"
description = "CreditChain executor service"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
creditchain-block-executor = { workspace = true }
creditchain-block-partitioner = { workspace = true }
creditchain-config = { workspace = true }
creditchain-infallible = { workspace = true }
creditchain-keygen = { workspace = true }
creditchain-language-e2e-tests = { workspace = true }
creditchain-logger = { workspace = true }
creditchain-metrics-core = { workspace = true }
creditchain-node-resource-metrics = { workspace = true }
creditchain-push-metrics =  { workspace = true }
creditchain-secure-net = { workspace = true }
creditchain-storage-interface = { workspace = true }
creditchain-transaction-simulation = { workspace = true }
creditchain-types = { workspace = true }
creditchain-vm = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
ctrlc = "3.4.0"
dashmap = { workspace = true }
itertools = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
creditchain-language-e2e-tests = { workspace = true }
creditchain-vm = { workspace = true }
