[package]
name = "DrandLottery"
version = "0.0.1"

[dependencies]
CreditChainFramework = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "creditchain-framework", rev = "mainnet" }
#CreditChainStdlib = { git = "https://github.com/creditchainorg/creditchain-framework.git", subdir = "creditchain-stdlib", rev = "mainnet" }


[addresses]
std = "0x1"
creditchain_std = "0x1"
creditchain_framework = "0x1"
drand = "_"
